function About() {
      return (
          <section
                id="about"
                      className="mx-auto max-w-6xl px-6 py-24"
                          >
                                <div className="grid gap-12 md:grid-cols-2 md:items-center">
                                        {/* Left */}
                                                <div>
                                                          <p className="mb-2 font-semibold uppercase tracking-widest text-cyan-400">
                                                                      About Me
                                                                                </p>

                                                                                          <h2 className="mb-6 text-4xl font-bold">
                                                                                                      Turning ideas into modern web applications.
                                                                                                                </h2>

                                                                                                                          <p className="mb-4 text-slate-400">
                                                                                                                                      I'm Bakari Hamisi, a frontend developer who enjoys building clean,
                                                                                                                                                  responsive, and user-friendly web applications.
                                                                                                                                                            </p>

                                                                                                                                                                      <p className="mb-4 text-slate-400">
                                                                                                                                                                                  My favorite tools include React, Vite, Tailwind CSS, JavaScript,
                                                                                                                                                                                              Node.js, Express, and Supabase.
                                                                                                                                                                                                        </p>

                                                                                                                                                                                                                  <p className="text-slate-400">
                                                                                                                                                                                                                              I believe great software combines beautiful design, performance,
                                                                                                                                                                                                                                          and a great user experience.
                                                                                                                                                                                                                                                    </p>
                                                                                                                                                                                                                                                            </div>

                                                                                                                                                                                                                                                                    {/* Right */}
                                                                                                                                                                                                                                                                            <div className="rounded-2xl border border-slate-800 bg-slate-900 p-8 shadow-lg">
                                                                                                                                                                                                                                                                                      <h3 className="mb-6 text-2xl font-bold text-cyan-400">
                                                                                                                                                                                                                                                                                                  Quick Facts
                                                                                                                                                                                                                                                                                                            </h3>

                                                                                                                                                                                                                                                                                                                      <div className="space-y-4">
                                                                                                                                                                                                                                                                                                                                  <div className="flex justify-between border-b border-slate-800 pb-2">
                                                                                                                                                                                                                                                                                                                                                <span>Name</span>
                                                                                                                                                                                                                                                                                                                                                              <span>Bakari Hamisi</span>
                                                                                                                                                                                                                                                                                                                                                                          </div>

                                                                                                                                                                                                                                                                                                                                                                                      <div className="flex justify-between border-b border-slate-800 pb-2">
                                                                                                                                                                                                                                                                                                                                                                                                    <span>Role</span>
                                                                                                                                                                                                                                                                                                                                                                                                                  <span>Frontend Developer</span>
                                                                                                                                                                                                                                                                                                                                                                                                                              </div>

                                                                                                                                                                                                                                                                                                                                                                                                                                          <div className="flex justify-between border-b border-slate-800 pb-2">
                                                                                                                                                                                                                                                                                                                                                                                                                                                        <span>Stack</span>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <span>React + Vite</span>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </div>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <div className="flex justify-between border-b border-slate-800 pb-2">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <span>Focus</span>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <span>Modern Web Apps</span>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </div>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <div className="flex justify-between">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <span>Brand</span>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <span className="text-cyan-400">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              GWIJITECH.dev
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </span>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </section>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      export default About;